# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fundatia Emil G. Racoviță
email: calin@cascaval.us
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: The Emil G. Racovita Foundation for Science and Extreme
             Environments

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.racoviță-foundation.ro" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  cc10512
show_downloads: false

default_lang: en
languages:
  en:
    title: "Emil G. Racovita Foundation"
  ro:
    title: "Fundația Emil G. Racoviță"
  fr:
    title: "La Fondation Emil G. Racovita"
  de:
    title: "Emil G. Racoviţă-Stiftung"

# Build settings
# theme: minima
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  # - jekyll-polyglot


# Polyglot configuration
#languages: ['ro', 'en', 'de', 'fr']
#default_lang: 'ro'
#exclude_from_localization: ['javascript', 'images', 'css']
#parallel_localization: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .gitignode
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
